
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: suyesh
  password: mustang4

development:
  <<: *default
  database: petro_future_dev



test:
  <<: *default
  database: petrox_future_test


production:
  <<: *default
  database: petrox_production
  username: petrox
  password: <%= ENV['PETROX_DATABASE_PASSWORD'] %>
