
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: petox_dev
  username: suyesh
  password: mustang4


test:
  <<: *default
  database: petox_test


production:
  <<: *default
  database: petrox_production
  username: petrox
  password: <%= ENV['PETROX_DATABASE_PASSWORD'] %>
